// Package pass implements the server side of humanymous Pass (SoT-36): the
// LLM-resistant interactive challenge served on a CHALLENGE verdict. This file is
// the security-critical core — instance generation and VERIFICATION — which lives
// entirely server-side (SoT-36 §2.4: "client collects, server decides").
//
// First mechanic: PHYSICS PLACEMENT (SoT-36 §4). The player places one ramp so a
// released ball reaches the cup after a chain reaction. It is chosen first because
// it is leak-resistant BY DESIGN: there is no stored "answer" to expose — the scene
// geometry may be public, yet solving still requires forward-simulating the physics
// (the VLATIM double-bind: plan AND ground AND simulate). Verification is a
// deterministic server-side re-simulation of the player's ramp; any placement that
// lands the ball in the cup passes (continuous, high-cardinality answer space).
//
// The instance is generated by working BACKWARD from a hidden "designed" ramp so a
// solution is guaranteed to exist, then the designed ramp is discarded — the player
// must find their own placement.
package pass

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/binary"
	"math"
)

// Mechanic identifies the challenge type (SoT-36 §4 rotates the primary per session).
type Mechanic string

const (
	MechanicPlacement Mechanic = "placement" // physics placement
)

// Vec is a 2D point/vector in the 0..100 challenge coordinate space.
type Vec struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

// Segment is a line segment obstacle the ball reflects off.
type Segment struct {
	A Vec `json:"a"`
	B Vec `json:"b"`
}

// Scene is the PUBLIC description sent to the client to render (SoT-36 §4: canvas,
// no answer in it). Knowing the scene does not give the answer — you must simulate.
type Scene struct {
	Mechanic   Mechanic  `json:"mechanic"`
	Gravity    float64   `json:"gravity"`
	Ball       Vec       `json:"ball"`      // release point
	Cup        Vec       `json:"cup"`       // cup center (target)
	CupR       float64   `json:"cupR"`      // cup capture radius
	Deflectors []Segment `json:"deflectors"` // fixed obstacles
	RampLen    float64   `json:"rampLen"`   // length of the ramp the player places
}

// physics constants (fixed so client and server agree; SoT-36 §2.4 server is truth).
const (
	dt        = 0.10
	maxSteps  = 900
	bounds    = 100.0
	rampBounce = 0.86 // energy retained on ramp bounce
	deflBounce = 0.90
)

// deriveSeed produces a per-instance 32-byte seed bound to the session + time bucket
// (mirrors internal/pow seeding; the masterKey never leaves the server).
func deriveSeed(masterKey []byte, sessionID string, bucket uint64) [32]byte {
	m := hmac.New(sha256.New, masterKey)
	var b [8]byte
	binary.BigEndian.PutUint64(b[:], bucket)
	m.Write([]byte("pass|"))
	m.Write([]byte(sessionID))
	m.Write([]byte{'|'})
	m.Write(b[:])
	var out [32]byte
	copy(out[:], m.Sum(nil))
	return out
}

// rng is a small deterministic stream PRNG (splitmix64) so an instance is fully
// reproducible from its seed for server-side verification.
type rng struct{ s uint64 }

func newRNG(seed [32]byte) *rng { return &rng{s: binary.BigEndian.Uint64(seed[:8]) | 1} }

func (r *rng) next() uint64 {
	r.s += 0x9E3779B97F4A7C15
	z := r.s
	z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9
	z = (z ^ (z >> 27)) * 0x94D049BB133111EB
	return z ^ (z >> 31)
}

// f returns a float in [lo, hi).
func (r *rng) f(lo, hi float64) float64 {
	return lo + (float64(r.next()>>11)/float64(1<<53))*(hi-lo)
}

// Generate builds a solvable physics-placement scene from a seed. It designs a
// hidden ramp, simulates to find where the ball lands, and puts the cup there —
// guaranteeing at least one solution exists — then returns only the public scene.
//
// difficulty (0..3, the blue controller's knob — SoT-36 §8) tightens the scene:
// higher difficulty means MORE deflectors (harder routing) and a SMALLER cup
// (tighter placement tolerance). It is served harder to suspicious sessions and
// trivial to likely-humans; Verify must be called with the SAME difficulty.
func Generate(masterKey []byte, sessionID string, bucket uint64, difficulty int) Scene {
	sc, _, _, _ := generate(masterKey, sessionID, bucket, difficulty)
	return sc
}

// generate is Generate plus the winning designed ramp (center + angle) — a
// GUARANTEED solution. Exposed to the verification path in tests so solvability is
// checked against a known answer, not a grid search.
func generate(masterKey []byte, sessionID string, bucket uint64, difficulty int) (Scene, float64, float64, float64) {
	if difficulty < 0 {
		difficulty = 0
	}
	if difficulty > 3 {
		difficulty = 3
	}
	seed := deriveSeed(masterKey, sessionID, bucket)
	r := newRNG(seed)

	sc := Scene{
		Mechanic: MechanicPlacement,
		Gravity:  r.f(9, 15),
		Ball:     Vec{X: r.f(12, 30), Y: r.f(6, 16)},
		CupR:     r.f(6.5, 8.5) - float64(difficulty)*0.9, // smaller cup = harder
		RampLen:  r.f(16, 22),
	}
	if sc.CupR < 3.8 {
		sc.CupR = 3.8
	}
	// 1..3 fixed deflectors in the mid-field, scaling with difficulty.
	n := 1 + difficulty
	if n > 3 {
		n = 3
	}
	for i := 0; i < n; i++ {
		cx, cy := r.f(35, 75), r.f(35, 65)
		ang := r.f(-0.9, 0.9)
		half := r.f(8, 13)
		dx, dy := math.Cos(ang)*half, math.Sin(ang)*half
		sc.Deflectors = append(sc.Deflectors, Segment{A: Vec{cx - dx, cy - dy}, B: Vec{cx + dx, cy + dy}})
	}

	// Place the cup where a hidden designed ramp sends the ball — AND require that
	// ramp to be NECESSARY: without it (natural path) the ball must clearly miss the
	// cup, so a wrong/absent ramp fails and the challenge cannot be passed trivially.
	// farRamp is off-canvas, so it never intersects — it stands in for "no ramp".
	farRamp := Segment{A: Vec{X: -30, Y: -30}, B: Vec{X: -30, Y: -29}}
	natural := simLand(sc, farRamp)
	// Keep the best (max-necessity) designed ramp as a guaranteed-solvable fallback:
	// whatever ramp we pick, ITS landing is reachable by that same ramp.
	var bestC Vec
	var bestA, bestMargin float64
	bestMargin = -1
	for attempt := 0; attempt < 24; attempt++ {
		c := Vec{X: r.f(28, 62), Y: r.f(38, 62)}
		a := r.f(-0.8, 0.3)
		land := simLand(sc, makeRamp(c, a, sc.RampLen))
		if land.X < 6 || land.X > 94 || land.Y < 18 { // landed off the useful field
			continue
		}
		margin := dist(natural, land)
		if margin > bestMargin {
			bestMargin, bestC, bestA = margin, c, a
		}
		if margin > sc.CupR+3 { // the ramp changed the outcome enough — accept now
			sc.Cup = land
			return sc, c.X, c.Y, a
		}
	}
	if bestMargin < 0 { // no valid designed landing at all (very rare) — gentle ramp
		bestC = Vec{X: sc.Ball.X + 8, Y: sc.Ball.Y + 28}
		bestA = 0.1
	}
	sc.Cup = simLand(sc, makeRamp(bestC, bestA, sc.RampLen)) // solvable by (bestC,bestA)
	return sc, bestC.X, bestC.Y, bestA
}

func clampF(v, lo, hi float64) float64 {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}

// simLand runs the ballistics WITHOUT cup capture and returns where the ball exits
// (leaves the field or comes to the end of the step budget) — used at generation
// time to decide where to put the cup and whether the ramp is necessary.
func simLand(sc Scene, ramp Segment) Vec {
	segs := append(append([]Segment{}, sc.Deflectors...), ramp)
	p := sc.Ball
	v := Vec{X: 0, Y: 0}
	for i := 0; i < maxSteps; i++ {
		v.Y += sc.Gravity * dt
		np := Vec{X: p.X + v.X*dt, Y: p.Y + v.Y*dt}
		for si, s := range segs {
			bounce := rampBounce
			if si < len(sc.Deflectors) {
				bounce = deflBounce
			}
			if hit, n := crosses(p, np, s); hit {
				v = reflectVel(v, n, bounce)
				np = Vec{X: p.X + v.X*dt*0.5, Y: p.Y + v.Y*dt*0.5}
				break
			}
		}
		p = np
		if p.X < 0 || p.X > bounds || p.Y > bounds {
			return p
		}
	}
	return p
}

// makeRamp builds a ramp segment centered at c with angle a and length len.
func makeRamp(c Vec, a, length float64) Segment {
	dx, dy := math.Cos(a)*length/2, math.Sin(a)*length/2
	return Segment{A: Vec{c.X - dx, c.Y - dy}, B: Vec{c.X + dx, c.Y + dy}}
}

// Verify re-simulates the player's ramp against the seed-derived scene and reports
// whether the ball reaches the cup. This is the whole verdict: no stored answer.
// bucket is the instance's issue bucket; currentBucket bounds staleness (TTL).
func Verify(masterKey []byte, sessionID string, bucket, currentBucket uint64, difficulty int, rampCX, rampCY, rampAngle float64) bool {
	if currentBucket < bucket || currentBucket-bucket > 2 { // TTL: a few buckets
		return false
	}
	sc := Generate(masterKey, sessionID, bucket, difficulty)
	ramp := makeRamp(Vec{X: rampCX, Y: rampCY}, rampAngle, sc.RampLen)
	// Reject a ramp placed on top of the ball or cup (degenerate) or out of bounds.
	if rampCX < 2 || rampCX > 98 || rampCY < 2 || rampCY > 98 {
		return false
	}
	if dist(Vec{rampCX, rampCY}, sc.Ball) < 4 {
		return false
	}
	land, ok := simulate(sc, ramp)
	return ok && dist(land, sc.Cup) <= sc.CupR
}

// simulate runs the deterministic ballistics: a point ball under gravity reflecting
// off the deflectors and the player's ramp. Returns the landing point (where it
// enters the cup or comes to rest / leaves) and whether it entered the cup.
func simulate(sc Scene, ramp Segment) (Vec, bool) {
	segs := append(append([]Segment{}, sc.Deflectors...), ramp)
	p := sc.Ball
	v := Vec{X: 0, Y: 0}
	for i := 0; i < maxSteps; i++ {
		v.Y += sc.Gravity * dt
		np := Vec{X: p.X + v.X*dt, Y: p.Y + v.Y*dt}
		// cup capture (check along the step)
		if dist(np, sc.Cup) <= sc.CupR || dist(p, sc.Cup) <= sc.CupR {
			return sc.Cup, true
		}
		// reflect off the first segment the path crosses
		bounced := false
		for si, s := range segs {
			bounce := rampBounce
			if si < len(sc.Deflectors) {
				bounce = deflBounce
			}
			if hit, n := crosses(p, np, s); hit {
				v = reflectVel(v, n, bounce)
				np = Vec{X: p.X + v.X*dt*0.5, Y: p.Y + v.Y*dt*0.5}
				bounced = true
				break
			}
		}
		_ = bounced
		p = np
		if p.X < 0 || p.X > bounds || p.Y > bounds {
			return p, false
		}
	}
	return p, false
}

func dist(a, b Vec) float64 { return math.Hypot(a.X-b.X, a.Y-b.Y) }

// crosses reports whether the segment p->q intersects wall, and the wall's unit normal.
func crosses(p, q Vec, wall Segment) (bool, Vec) {
	if !segIntersect(p, q, wall.A, wall.B) {
		return false, Vec{}
	}
	wx, wy := wall.B.X-wall.A.X, wall.B.Y-wall.A.Y
	l := math.Hypot(wx, wy)
	if l == 0 {
		return false, Vec{}
	}
	// normal is perpendicular to the wall
	return true, Vec{X: -wy / l, Y: wx / l}
}

// reflect reflects velocity v about the wall normal n, scaled by restitution.
func reflectVel(v, n Vec, rest float64) Vec {
	d := v.X*n.X + v.Y*n.Y
	return Vec{X: (v.X - 2*d*n.X) * rest, Y: (v.Y - 2*d*n.Y) * rest}
}

func segIntersect(p1, p2, p3, p4 Vec) bool {
	d1 := cross(sub(p3, p4), sub(p3, p1))
	d2 := cross(sub(p3, p4), sub(p3, p2))
	d3 := cross(sub(p1, p2), sub(p1, p3))
	d4 := cross(sub(p1, p2), sub(p1, p4))
	return ((d1 > 0) != (d2 > 0)) && ((d3 > 0) != (d4 > 0))
}

func sub(a, b Vec) Vec     { return Vec{a.X - b.X, a.Y - b.Y} }
func cross(a, b Vec) float64 { return a.X*b.Y - a.Y*b.X }
