// Package pass implements the server side of humanymous Pass (SoT-36): the
// LLM-resistant interactive challenge served on a CHALLENGE verdict. This file is
// the security-critical core — instance generation and VERIFICATION — which lives
// entirely server-side (SoT-36 §2.4: "client collects, server decides").
//
// First mechanic: PHYSICS PLACEMENT (SoT-36 §4). The player places one ramp so a
// released ball reaches the cup after a chain reaction. It is chosen first because
// it is leak-resistant BY DESIGN: there is no stored "answer" to expose — the scene
// geometry may be public, yet solving still requires forward-simulating the physics
// (the VLATIM double-bind: plan AND ground AND simulate). Verification is a
// deterministic server-side re-simulation of the player's ramp; any placement that
// lands the ball in the cup passes (continuous, high-cardinality answer space).
//
// The instance is generated by working BACKWARD from a hidden "designed" ramp so a
// solution is guaranteed to exist, then the designed ramp is discarded — the player
// must find their own placement.
package pass

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/binary"
	"math"
)

// Mechanic identifies the challenge type (SoT-36 §4 rotates the primary per session).
type Mechanic string

const (
	MechanicPlacement Mechanic = "placement" // physics placement
)

// Vec is a 2D point/vector in the 0..100 challenge coordinate space.
type Vec struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

// Segment is a line segment obstacle the ball reflects off.
type Segment struct {
	A Vec `json:"a"`
	B Vec `json:"b"`
}

// Scene is the PUBLIC description sent to the client to render (SoT-36 §4: canvas,
// no answer in it). Knowing the scene does not give the answer — you must simulate.
type Scene struct {
	Mechanic   Mechanic  `json:"mechanic"`
	Gravity    float64   `json:"gravity"`
	Ball       Vec       `json:"ball"`      // release point
	Cup        Vec       `json:"cup"`       // cup center (target)
	CupR       float64   `json:"cupR"`      // cup capture radius
	Deflectors []Segment `json:"deflectors"` // fixed obstacles
	RampLen    float64   `json:"rampLen"`   // length of the ramp the player places
}

// physics constants (fixed so client and server agree; SoT-36 §2.4 server is truth).
const (
	dt        = 0.10
	maxSteps  = 900
	bounds    = 100.0
	rampBounce = 0.86 // energy retained on ramp bounce
	deflBounce = 0.90
)

// deriveSeed produces a per-instance 32-byte seed bound to the session + time bucket
// (mirrors internal/pow seeding; the masterKey never leaves the server).
func deriveSeed(masterKey []byte, sessionID string, bucket uint64) [32]byte {
	m := hmac.New(sha256.New, masterKey)
	var b [8]byte
	binary.BigEndian.PutUint64(b[:], bucket)
	m.Write([]byte("pass|"))
	m.Write([]byte(sessionID))
	m.Write([]byte{'|'})
	m.Write(b[:])
	var out [32]byte
	copy(out[:], m.Sum(nil))
	return out
}

// rng is a small deterministic stream PRNG (splitmix64) so an instance is fully
// reproducible from its seed for server-side verification.
type rng struct{ s uint64 }

func newRNG(seed [32]byte) *rng { return &rng{s: binary.BigEndian.Uint64(seed[:8]) | 1} }

func (r *rng) next() uint64 {
	r.s += 0x9E3779B97F4A7C15
	z := r.s
	z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9
	z = (z ^ (z >> 27)) * 0x94D049BB133111EB
	return z ^ (z >> 31)
}

// f returns a float in [lo, hi).
func (r *rng) f(lo, hi float64) float64 {
	return lo + (float64(r.next()>>11)/float64(1<<53))*(hi-lo)
}

// Generate builds a solvable physics-placement scene from a seed. It designs a
// hidden ramp, simulates to find where the ball lands, and puts the cup there —
// guaranteeing at least one solution exists — then returns only the public scene.
//
// difficulty (0..3, the blue controller's knob — SoT-36 §8) tightens the scene:
// higher difficulty means MORE deflectors (harder routing) and a SMALLER cup
// (tighter placement tolerance). It is served harder to suspicious sessions and
// trivial to likely-humans; Verify must be called with the SAME difficulty.
func Generate(masterKey []byte, sessionID string, bucket uint64, difficulty int) Scene {
	sc, _, _, _ := generate(masterKey, sessionID, bucket, difficulty)
	return sc
}

// generate is Generate plus the winning designed ramp (center + angle) — a
// GUARANTEED solution. Exposed to the verification path in tests so solvability is
// checked against a known answer, not a grid search.
func generate(masterKey []byte, sessionID string, bucket uint64, difficulty int) (Scene, float64, float64, float64) {
	if difficulty < 0 {
		difficulty = 0
	}
	if difficulty > 3 {
		difficulty = 3
	}
	seed := deriveSeed(masterKey, sessionID, bucket)
	r := newRNG(seed)
	farRamp := Segment{A: Vec{X: -30, Y: -30}, B: Vec{X: -30, Y: -29}}
	fullCupR := r.f(6.5, 8.5) - float64(difficulty)*0.9 // smaller cup = harder
	if fullCupR < 3.8 {
		fullCupR = 3.8
	}

	// Outer re-roll: keep generating fresh scenes (ball + deflectors) until one admits
	// a clean, NECESSARY, VISIBLE cup at full size — a scene whose natural (no-ramp)
	// fall does not already pass through the target zone. Almost always succeeds on the
	// first roll; the loop only exists for the rare bad geometry. Deterministic: Verify
	// runs the same seed → same rolls → same scene.
	var gScene Scene
	var gCX, gCY, gA, gMargin float64
	var gCup Vec
	gMargin = -1
	for outer := 0; outer < 24; outer++ {
		sc := Scene{Mechanic: MechanicPlacement, Gravity: r.f(9, 15),
			Ball: Vec{X: r.f(12, 30), Y: r.f(6, 16)}, CupR: fullCupR, RampLen: r.f(16, 22)}
		n := 1 + difficulty
		if n > 3 {
			n = 3
		}
		for i := 0; i < n; i++ {
			cx, cy, ang, half := r.f(35, 75), r.f(35, 65), r.f(-0.9, 0.9), r.f(8, 13)
			dx, dy := math.Cos(ang)*half, math.Sin(ang)*half
			sc.Deflectors = append(sc.Deflectors, Segment{A: Vec{cx - dx, cy - dy}, B: Vec{cx + dx, cy + dy}})
		}
		for attempt := 0; attempt < 40; attempt++ {
			// The designed ramp goes DIRECTLY in the ball's fall path so it deflects it
			// (otherwise the designed path == the natural path and the ramp isn't needed).
			c := Vec{X: clampF(sc.Ball.X+r.f(-7, 12), 10, 90), Y: sc.Ball.Y + r.f(16, 40)}
			a := r.f(-0.95, 0.6)
			cup, okT := pickVisibleTarget(simPath(sc, makeRamp(c, a, sc.RampLen)))
			if !okT {
				continue
			}
			margin := pathMinDist(sc, farRamp, cup) // closest the no-ramp path gets to the cup
			if margin > sc.CupR+2 {                 // clean, full-size, necessary — done
				sc.Cup = cup
				return sc, c.X, c.Y, a
			}
			if margin > gMargin { // remember the best across all rolls as a safety net
				gMargin, gScene, gCX, gCY, gA, gCup = margin, sc, c.X, c.Y, a, cup
			}
		}
	}
	// 24 rolls without a clean scene is astronomically rare. Use the best seen with the
	// cup radius held STRICTLY below its necessity margin (a wrong ramp still misses).
	sc := gScene
	sc.Cup = gCup
	if gMargin < 0.2 {
		gMargin = 0.2
	}
	if cap := gMargin * 0.72; cap < sc.CupR {
		sc.CupR = cap
	}
	return sc, gCX, gCY, gA
}

// simPath runs the ballistics WITHOUT cup capture and returns the full trajectory.
func simPath(sc Scene, ramp Segment) []Vec {
	segs := append(append([]Segment{}, sc.Deflectors...), ramp)
	p := sc.Ball
	v := Vec{X: 0, Y: 0}
	path := []Vec{p}
	for i := 0; i < maxSteps; i++ {
		v.Y += sc.Gravity * dt
		np := Vec{X: p.X + v.X*dt, Y: p.Y + v.Y*dt}
		for si, s := range segs {
			bounce := rampBounce
			if si < len(sc.Deflectors) {
				bounce = deflBounce
			}
			if hit, n := crosses(p, np, s); hit {
				v = reflectVel(v, n, bounce)
				np = Vec{X: p.X + v.X*dt*0.5, Y: p.Y + v.Y*dt*0.5}
				break
			}
		}
		p = np
		path = append(path, p)
		if p.X < 0 || p.X > bounds || p.Y > bounds {
			break
		}
	}
	return path
}

// pickVisibleTarget returns the DEEPEST point of the trajectory that sits in the
// visible target band (inset from every edge, lower-middle), so the cup renders
// clearly and reads as a place the ball travels TO. False if the path never enters it.
func pickVisibleTarget(path []Vec) (Vec, bool) {
	var best Vec
	found := false
	for i, p := range path {
		if i < 4 { // skip the release neighborhood
			continue
		}
		if p.X >= 14 && p.X <= 86 && p.Y >= 52 && p.Y <= 86 {
			best = p // keep the last (deepest along the path) qualifying point
			found = true
		}
	}
	return best, found
}

// pathMinDist returns the minimum distance from the ball's path (under ramp) to
// target, measured continuously over each step segment (not just sampled points).
func pathMinDist(sc Scene, ramp Segment, target Vec) float64 {
	path := simPath(sc, ramp)
	min := 1e9
	for i := 1; i < len(path); i++ {
		if d := distToSeg(target, path[i-1], path[i]); d < min {
			min = d
		}
	}
	if len(path) == 1 {
		return dist(path[0], target)
	}
	return min
}

func clampF(v, lo, hi float64) float64 {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}

// makeRamp builds a ramp segment centered at c with angle a and length len.
func makeRamp(c Vec, a, length float64) Segment {
	dx, dy := math.Cos(a)*length/2, math.Sin(a)*length/2
	return Segment{A: Vec{c.X - dx, c.Y - dy}, B: Vec{c.X + dx, c.Y + dy}}
}

// Verify re-simulates the player's ramp against the seed-derived scene and reports
// whether the ball reaches the cup. This is the whole verdict: no stored answer.
// bucket is the instance's issue bucket; currentBucket bounds staleness (TTL).
func Verify(masterKey []byte, sessionID string, bucket, currentBucket uint64, difficulty int, rampCX, rampCY, rampAngle float64) bool {
	if currentBucket < bucket || currentBucket-bucket > 2 { // TTL: a few buckets
		return false
	}
	sc := Generate(masterKey, sessionID, bucket, difficulty)
	ramp := makeRamp(Vec{X: rampCX, Y: rampCY}, rampAngle, sc.RampLen)
	// Reject a ramp placed on top of the ball or cup (degenerate) or out of bounds.
	if rampCX < 2 || rampCX > 98 || rampCY < 2 || rampCY > 98 {
		return false
	}
	if dist(Vec{rampCX, rampCY}, sc.Ball) < 4 {
		return false
	}
	land, ok := simulate(sc, ramp)
	return ok && dist(land, sc.Cup) <= sc.CupR
}

// simulate runs the deterministic ballistics: a point ball under gravity reflecting
// off the deflectors and the player's ramp. Returns the landing point (where it
// enters the cup or comes to rest / leaves) and whether it entered the cup.
func simulate(sc Scene, ramp Segment) (Vec, bool) {
	segs := append(append([]Segment{}, sc.Deflectors...), ramp)
	p := sc.Ball
	v := Vec{X: 0, Y: 0}
	for i := 0; i < maxSteps; i++ {
		v.Y += sc.Gravity * dt
		np := Vec{X: p.X + v.X*dt, Y: p.Y + v.Y*dt}
		// cup capture — measured along the whole step so a fast ball can't tunnel over.
		if distToSeg(sc.Cup, p, np) <= sc.CupR {
			return sc.Cup, true
		}
		// reflect off the first segment the path crosses
		bounced := false
		for si, s := range segs {
			bounce := rampBounce
			if si < len(sc.Deflectors) {
				bounce = deflBounce
			}
			if hit, n := crosses(p, np, s); hit {
				v = reflectVel(v, n, bounce)
				np = Vec{X: p.X + v.X*dt*0.5, Y: p.Y + v.Y*dt*0.5}
				bounced = true
				break
			}
		}
		_ = bounced
		p = np
		if p.X < 0 || p.X > bounds || p.Y > bounds {
			return p, false
		}
	}
	return p, false
}

func dist(a, b Vec) float64 { return math.Hypot(a.X-b.X, a.Y-b.Y) }

// distToSeg is the distance from point p to the segment a→b. Used for cup capture
// and necessity so a fast ball can't tunnel over a small cup between steps, and the
// no-ramp path is measured continuously (not just at sampled points).
func distToSeg(p, a, b Vec) float64 {
	ab := sub(b, a)
	ab2 := ab.X*ab.X + ab.Y*ab.Y
	if ab2 == 0 {
		return dist(p, a)
	}
	ap := sub(p, a)
	t := (ap.X*ab.X + ap.Y*ab.Y) / ab2
	if t < 0 {
		t = 0
	} else if t > 1 {
		t = 1
	}
	return dist(p, Vec{X: a.X + t*ab.X, Y: a.Y + t*ab.Y})
}

// crosses reports whether the segment p->q intersects wall, and the wall's unit normal.
func crosses(p, q Vec, wall Segment) (bool, Vec) {
	if !segIntersect(p, q, wall.A, wall.B) {
		return false, Vec{}
	}
	wx, wy := wall.B.X-wall.A.X, wall.B.Y-wall.A.Y
	l := math.Hypot(wx, wy)
	if l == 0 {
		return false, Vec{}
	}
	// normal is perpendicular to the wall
	return true, Vec{X: -wy / l, Y: wx / l}
}

// reflect reflects velocity v about the wall normal n, scaled by restitution.
func reflectVel(v, n Vec, rest float64) Vec {
	d := v.X*n.X + v.Y*n.Y
	return Vec{X: (v.X - 2*d*n.X) * rest, Y: (v.Y - 2*d*n.Y) * rest}
}

func segIntersect(p1, p2, p3, p4 Vec) bool {
	d1 := cross(sub(p3, p4), sub(p3, p1))
	d2 := cross(sub(p3, p4), sub(p3, p2))
	d3 := cross(sub(p1, p2), sub(p1, p3))
	d4 := cross(sub(p1, p2), sub(p1, p4))
	return ((d1 > 0) != (d2 > 0)) && ((d3 > 0) != (d4 > 0))
}

func sub(a, b Vec) Vec     { return Vec{a.X - b.X, a.Y - b.Y} }
func cross(a, b Vec) float64 { return a.X*b.Y - a.Y*b.X }
