// Command gen-demo-keys mints the DEMO keypairs the optional PLAN-08 trust-upgrade
// overlays (privacypass, webauthn) need, into their gitignored locations. It exists
// so those e2e flows are reproducible from a fresh clone WITHOUT committing any key
// material (private keys must never be committed; the public halves are regenerated
// deterministically here).
//
//	go run ./scripts/gen-demo-keys
//	docker compose -f deployments/compose.yaml -f deployments/compose/privacypass.yaml up -d origin gate
//	node scripts/assert-privacypass.mjs
//
// These are DEMO keys — a real deployment supplies real issuer/credential keys.
package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	// Privacy Pass PAT issuer (RSA-2048): public PEM for the gate allowlist, private PEM for the signer.
	rsaKey, err := rsa.GenerateKey(rand.Reader, 2048)
	must(err)
	writePEM("deployments/patissuers/issuer.pem", "PUBLIC KEY", mustDER(x509.MarshalPKIXPublicKey(&rsaKey.PublicKey)))
	writePEM("deployments/patissuers/issuer-priv.pem", "PRIVATE KEY", mustDER(x509.MarshalPKCS8PrivateKey(rsaKey)))

	// WebAuthn credential (ECDSA P-256): allowlist line (credentialId + base64url SPKI) + private PEM.
	ecKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	must(err)
	spki := mustDER(x509.MarshalPKIXPublicKey(&ecKey.PublicKey))
	writeFile("deployments/webauthncreds/creds.txt",
		"# PLAN-08 R2 WebAuthn DEMO credential (credentialId  base64url-spki-ec-p256). Generated by scripts/gen-demo-keys.\n"+
			"demo-credential-1 "+base64.RawURLEncoding.EncodeToString(spki)+"\n")
	writePEM("deployments/webauthncreds/cred-priv.pem", "PRIVATE KEY", mustDER(x509.MarshalPKCS8PrivateKey(ecKey)))

	fmt.Println("demo keys written: deployments/patissuers/{issuer.pem,issuer-priv.pem}, deployments/webauthncreds/{creds.txt,cred-priv.pem}")
}

func writePEM(path, typ string, der []byte) {
	must(os.MkdirAll(filepath.Dir(path), 0o755))
	// A PUBLIC key is bind-mounted read-only into the distroless, NON-ROOT gate
	// container (e.g. patissuers/issuer.pem for -pat-issuers), so it must be
	// world-readable or the container user gets "permission denied" and the gate
	// fails to start. Private keys are host-only (the assert-side signer) and stay
	// owner-only. (Local Docker Desktop ignores these Unix perms; a Linux CI runner
	// enforces them — this is what surfaced the overlay failure.)
	mode := os.FileMode(0o600)
	if typ == "PUBLIC KEY" {
		mode = 0o644
	}
	must(os.WriteFile(path, pem.EncodeToMemory(&pem.Block{Type: typ, Bytes: der}), mode))
}

func writeFile(path, content string) {
	must(os.MkdirAll(filepath.Dir(path), 0o755))
	must(os.WriteFile(path, []byte(content), 0o644))
}

func mustDER(der []byte, err error) []byte { must(err); return der }

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-demo-keys:", err)
		os.Exit(1)
	}
}
